# Generated by Django 4.1 on 2022-09-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='conteudo',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='reclamacao',
            field=models.IntegerField(),
        ),
    ]
