# Generated by Django 4.1 on 2022-09-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='login',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
